### ISSUE TITLE
Cannot compile remantle.c

### ISSUE THREAD

**Issue by Skkkitzo** [PegasusEpsilon/foundation-package-tools#2]
When compiling remantle.c with `gcc -std=c99 remantle.c utils.o -o remantle` it gives multiple errors seen in [this screenshot](https://i.imgur.com/dOvcYr7.png).

Yes I did issue `gcc -std=c99 utils.c -c` beforehand.

I tried fixing the `fdopen` issue by replacing it with `fopen` but that fixed nothing.

**Comment by PegasusEpsilon** [comment]
Line 104 is supposed to call `fdopen`. Changing it to `fopen` is an error you created.

The functions `fdopen` and `fileno` are not available unless declaring `_POSIX_C_SOURCE`, which is why that's done on line 1.

If that `#define` is not there, or it's been removed, or it's been moved to a lower line, fix that, and your problems should go away. If it's still there, or that doesn't fix it, then something's wrong with your setup, and I need more details about that to help. But this isn't the place for that, either. That's why I'm still in the foundation discord, and I don't even own the game.
